name: skill_track_db
description: A sample command-line application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  sqflite: ^2.4.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
